// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrsggituwyibyxpoocyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyc2dnaXR1d3lpYnl4cG9vY3lvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMDM1NzcsImV4cCI6MjA2NjY3OTU3N30.8VKY8GLwgIHVtFGmSASz9IssCCd4lj78M3m9ddL7owc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);